version: "3.9"
services:
  backend:
    build: ./server
    restart: always
    ports:
      - "7777:7777"
    depends_on:
      - db
    env_file:
      - ./server/.env
    networks:
      - app
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env
    networks:
      - app
volumes:
  postgres_data:
    driver: local
networks:
  app:
    driver: bridge